check the size of properties.
rivo/uniseg pull request #38
Opened 2023-07-23 04:04 UTC by shogo82148

[propertySearch](https://github.com/rivo/uniseg/blob/ac807292cb7cacfe6d6227ea7c5793c4acd31b88/properties.go#L134-L155) may overflow if `len(properties) >= 1<<31`.
See also: https://github.com/rivo/uniseg/pull/37

2023-07-24 16:01 UTC, rivo requested changes

2023-07-30 08:50 UTC, rivo requested changes

2023-07-30 08:50 UTC, rivo commented on gen_properties.go
> +		// see https://github.com/rivo/uniseg/pull/37
Please remove the link, too.

2023-07-30 14:50 UTC, shogo82148 commented on gen_properties.go
> +		// see https://github.com/rivo/uniseg/pull/37
```suggestion
```

2023-07-30 14:51 UTC, shogo82148 commented on gen_properties.go
> +		// see https://github.com/rivo/uniseg/pull/37
removed

2023-07-30 20:25 UTC, merged